name: WakaTime Readme Stats

on:
  # update once a day
  schedule:
    - cron: "30 18 * * *"
  # allow manual runs from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: update readme with wakatime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TARGET_PATH: README.md
          SHOW_TITLE: "true"
          BLOCKS: "->"
          TIME_RANGE: all_time
